adjective1 = input("Enter an adjective: ")
adjective2 = input("Enter a second adjective: ")
adjective3 = input("Enter a third adjective: ")
noun = input("Enter a noun: ")
verb = input("Enter a verb: ")

print(f"Today, I went to a {adjective1} zoo")
print(f"In an exhibit, I saw {noun}")
print(f"{noun} was {adjective2} and {verb}ing")
print(f"I was {adjective3}")
